name: check-links
on:
  push:
    branches:
      - main
      - 'aws-cwa-*'
  pull_request:

# Do not cancel this workflow on main. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16616
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=tcort/markdown-link-check
  MD_LINK_CHECK_VERSION: "3.12.2"

jobs:
  changedfiles:
    name: changed files
    runs-on: ubuntu-latest
    env:
      PR_HEAD: ${{ github.event.pull_request.head.sha }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    outputs:
      files: ${{ steps.changes.outputs.files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        run: |
          files=$(git diff --name-only --diff-filter=ACMRTUXB $(git merge-base origin/main $PR_HEAD) $PR_HEAD | grep .md$ | xargs)

          if [ -z "$files" ] && git diff --name-only $(git merge-base origin/main $PR_HEAD) $PR_HEAD | grep -q "package.json"; then
            files="**/*.md"
          fi

          echo "files=$files" >> $GITHUB_OUTPUT

